### ISSUE TITLE
Unexpected error; Failure("Impossible: parameter must be a variable")

### ISSUE THREAD

**Issue by A-Manning** [FStarLang/FStar#1090]
```
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: parameter must be a variable")
```
Simplified code that triggers this error is below.

```
type idx (n:nat) =
  | Idx0 : idx 0
  | Inc : m:nat -> idx m -> idx (m+1)
```

**Comment by kyoDralliam** [comment]
The error says exactly what's the problem but should really be clarified : a parameter is fixed for every constructor (so in your case it should be the variable `n` in both cases) whereas what you want is an index.

```
type idx : nat -> Type =
  | Idx0 : idx 0
  | Inc : #n:nat -> idx n -> idx (n+1)
```

**Comment by catalin-hritcu** [comment]
For a start this should fail cleanly, then we can also improve the error message.

**Comment by kyoDralliam** [comment]
I changed the failure to a proper error which is hopefully more readable.

**Comment by catalin-hritcu** [comment]
@kyoDralliam   I'm a bit confused. Still getting the same error message for the code above:
```
$ fstar.exe bug1090.fst
Unexpected error; please file a bug report, ideally with a minimized version of the source program that triggered the error.
Failure("Impossible: parameter must be a variable")
$ fstar.exe --version
F* 0.9.4.3
platform=Linux_x86_64
compiler=OCaml 4.02.3
date=2017-06-21T19:22:11+02:00
commit=ba94f8330 (dirty)

```

**Comment by catalin-hritcu** [comment]
Nevermind, I was confused about my branches. The error message is good now:
```
$ fstar.exe bug1090.fst
./bug1090.fst(4,15-4,16): (Error) Inductive type parameter 0 must be a variable ; You may want to change it to an index.
1 error was reported (see above)
```
